---
ServerApi:
  Address: 10.0.2.15
  Port: 24601
AgentApi:
  InsecureAddr: 10.10.10.9
  InsecurePort: 24602
AssetServer:
  Addr: 10.10.10.9
  Port: 8080
  BaseDir: "/var/vaquero/files"
  Scheme: http
SavePath: "/var/vaquero/save"
Gitter:
  Endpoint: "/postreceive"
  Timeout: 2
  Addr: 10.0.2.15
  Port: 9090
GitHook:
- ID: vaquero-vagrant
  Token: <GIT_TOKEN> 
  URL: https://github.com/gem-test/vaquero
  Secret: supersecretcode
SoT:
- Git:
    HookID: vaquero-vagrant
    ID: vaquero-vagrant
    Branch: vagrant
Log:
  Level: debug
  Location: stdout
  Type: text
