branches:
  exclude:
    - gh-pages
    - VagrantEnv

pipeline:
  build:
    image: gemtest/vaquero-docs:0.1
    commands:
      - ./tools/convert.sh

  merge:
    image: gemtest/vaquero-docs:0.1
    commands:
      - ./tools/merge.sh

  publish:
    image: plugins/git-push
    remote: git@github.com:CiscoCloud/vaquero-docs
    remote_name: upstream
    branch: gh-pages
    commit: true
