swagger: '2.0'
info:
  title: Vaquero User API
  description: Experimental API for user interactions with Vaquero
  version: "0.0.1"
schemes:
  - http
paths:
  /override:
    post:
      summary: Override host current boot
      description: |
        Specify a new boot for the given host. Requires site id, host, and target boot. Host must exist in site, and boot must exist in host workflow.
      parameters:
        - name: site
          in: query
          description: Site ID
          required: true
          type: string
        - name: host
          in: query
          description: Host identifier (usually MAC)
          required: true
          type: string
        - name: boot
          in: query
          description: Target boot for host
          required: true
          type: string
      tags:
        - Models
      responses:
        200:
          description: Host current boot reset correctly
        400:
          description: One or more required parameters missing
